---
- name: Reboot machines
  hosts: Ubuntu

  tasks:
    -name: Show rebooting host
      ansible.builtin.debug:
        msg: "{{inventory_hostname}} is rebooting..."

    -name: Reboot
      ansible.builtin.Reboot

    -name: show online host
      ansible.builtin.debug:
        msg: "{{inventory_hostname}} is online"